### ISSUE TITLE
Skip directories when globbing

### ISSUE THREAD

**Issue by Kansattica** [alexellis/upload-assets#1]
Hello! I've been working with your github action, and I've run into an issue. When dealing with nested directories (such as the ones that download-artifact makes when dealing with multiple artifacts), trying to glob over them with something like `artifacts/**/*` attempts to read the directories and errors out, as seen here: https://github.com/Kansattica/msync/runs/1357436578?check_suite_focus=true

Note that it's trying to upload the directory, `artifacts/msync-vtesttime-install-linux-x64-gcc`, as well as the file inside with the same name, and fails before it can get there.

I've worked around this by flattening the directory before uploading, but I figured I'd file an issue anyways. Thank you!

**Comment by alexellis** [comment]
I think this can be fixed in the loop. Are you wanting to send in a tested PR for merge into the repo?

**Comment by Kansattica** [comment]
I can if you want, but I won't be able to work on it until Monday at the earliest.

**Comment by alexellis** [comment]
That works for me.
