### ISSUE TITLE
socket hang up when using this action

### ISSUE THREAD

**Issue by taori** [alexellis/upload-assets#5]
I am running into the following issue when your action is executed:

![grafik](https://user-images.githubusercontent.com/5545184/126900972-c4b37b60-7e73-408f-86bd-994080b39f5a.png)

Have you run into this issue before and have an idea how to solve it?

**Comment by taori** [comment]
@alexellis any ideas?

**Comment by nazar-pc** [comment]
I spent multiple hours and finally found the reason. Job needs to have `permissions.contents: write` in it, then it works.

**Comment by alexellis** [comment]
Thanks @nazar-pc :+1: 

I ran into this recently. I'm not really sure why permissions.contents: write is required to add artifacts, but I'll update the README to help others understand.

My sense is that GitHub added the RBAC set after this plugin was written.

**Comment by alexellis** [comment]
Closing with note added here: https://github.com/alexellis/upload-assets/commit/8507d1cb61f331f9d5b4552e2d698d92831a0ad3
