### ISSUE TITLE
Upgrade to node16

### ISSUE THREAD

**Issue by Traphalet** [alexellis/upload-assets#8]
Extract from [Github.blog](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/):

> Node 12 has been out of support since [April 2022](https://github.com/nodejs/Release/#end-of-life-releases), as a result we have started the deprecation process of Node 12 for GitHub Actions. We plan to migrate all actions to run on Node16 by Summer 2023. We will monitor the progress of the migration and listen to the community for how things are going before we define a final date.
To raise awareness of the upcoming change, we are adding a warning into workflows which contain Actions running on Node 12. This will come into effect starting on September 27th.

**Comment by alexellis** [comment]
Thanks for the note. Would you like to send a PR?

**Comment by alexellis** [comment]
@Traphalet I've done this in 0.4.0, if you're using this action [please sponsor me](https://github.com/sponsors/alexellis) or [check out my eBooks](https://store.openfaas.com/).
